import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })
const str = 'https://media.giphy.com/media/iHD88spVFkL7mZakwa/giphy.gif'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
      <iframe src="https://giphy.com/embed/iHD88spVFkL7mZakwa" width="480" height="480" frameBorder="0" className={styles.soon} allowFullScreen></iframe><p><a href="https://giphy.com/gifs/iHD88spVFkL7mZakwa">via GIPHY</a></p>
      </main>
    </>
  )
}
